### PR TITLE
Add flex properties

### PR DESCRIPTION
**Pull request by iamdustan**
For `flex` support in [RCSS](https://github.com/chenglou/rcss).

### CODE REVIEW

**Comment by chenglou** [comment]
Thanks! RCSS dependency updated.

**Comment by chenglou** [comment]
Oops, actually I shouldn't have merged this. We should use the actual css properties, e.g. `flex-basis`. I'll fix that.

**Comment by iamdustan** [comment]
Ah. I was thinking this set through `domElement.style.styleProp`. I should’ve looked a bit closer.

Thanks!

**Comment by iamdustan** [comment]
Will the dep update to RCSS include a version bump and publish or should I just go off the git hash for now?

**Comment by chenglou** [comment]
It's already bumped. In master right now.
I won't release a new RCSS version soon though.

**Comment by iamdustan** [comment]
roger that.

**Pull request merged**
